### ISSUE TITLE
Calling vklGetFramebuffer for valid input indices results in VKL_EXIT_WITH_ERROR 

### ISSUE THREAD

**Issue by dforkert** [cg-tuwien/VulkanLaunchpad#22]
The check in `vklGetFramebuffer(uint32_t i)` whether the input index `i` is out of bounds uses the comparison `mFramebuffers.size() >= i`. This causes the function to trigger VKL_EXIT_WITH_ERROR for valid indices instead of _out of bounds_ indices. 
Changing the comparison to `mFramebuffers.size() <= i` should fix this issue.
This issue is also present in the ECG framework.

**Comment by johannesugb** [comment]
Uh oh, thanks for pointing it out.
Do these changes look good to you: https://github.com/cg-tuwien/VulkanLaunchpad/pull/23 ?

**Comment by dforkert** [comment]
Now `vklGetFramebuffer(uint32_t i)` throws an error, precisely, when `i` is out of bounds, which is expected behaviour.
